"""add user permission

Revision ID: 31dab84ba4f0
Revises: None
Create Date: 2016-08-08 10:09:06.653729

"""

# revision identifiers, used by Alembic.
revision = '31dab84ba4f0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'default_city')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('default_city', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
